'use strict';
const $ = id => document.getElementById(id);
let token = '', selected = null, config;
const states = {OPEN:'待查核',ACKNOWLEDGED:'已受理',RETURNED:'退回修正',WAIT_SOURCE:'待官方補件',REJECTED:'本版已駁回',READY_REVIEW:'復驗通過，待簽核',PUBLISHING:'發布處理中',PUBLISHED:'已發布結案',CONFLICT:'版本競爭，需重驗',CLOSED_NO_CHANGE:'已結案，資料未變更'};
function message(text, error=false){$('message').textContent=text;$('message').className=error?'error':'';}
function el(tag, text, cls){const x=document.createElement(tag);x.textContent=text;if(cls)x.className=cls;return x;}
function random(){return btoa(String.fromCharCode(...crypto.getRandomValues(new Uint8Array(32)))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
async function api(path, options={}){const r=await fetch(path,{...options,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(options.headers||{})}});if(!r.ok){let b=await r.json();throw Error(b.error||'系統無法完成要求');}return r;}
async function login(){const verifier=random(),state=random();const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier));const challenge=btoa(String.fromCharCode(...new Uint8Array(hash))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');sessionStorage.setItem('ntpc-review-oauth',JSON.stringify({verifier,state,at:Date.now()}));const q=new URLSearchParams({response_type:'code',client_id:config.client_id,redirect_uri:config.redirect_uri,scope:config.scope,state,code_challenge:challenge,code_challenge_method:'S256'});location.assign(config.login_origin+'/oauth2/authorize?'+q);}
async function list(){message('正在讀取案件…');const data=await (await api('/api/review/cases')).json();$('cases').replaceChildren();for(const c of data.cases){const b=el('button','', 'case');b.append(el('strong',states[c.status]||c.status),el('small',c.case_id),el('small',`${c.issue_count} 個問題｜修訂 ${c.revision}`));b.addEventListener('click',()=>loadCase(c.case_id).catch(e=>message(e.message,true)));$('cases').append(b);}if(!data.cases.length)$('cases').textContent='目前沒有異常案件。';message('案件已更新。');}
async function loadCase(id){selected=await(await api('/api/review/cases/'+encodeURIComponent(id))).json();const c=selected;$('heading').textContent=states[c.status]||c.status;$('detail').replaceChildren();const dl=document.createElement('dl');for(const [k,v] of [['案件',c.case_id],['修訂',c.revision],['候選雜湊',c.candidate?.manifest_sha256||'尚未取得'],['復驗執行',c.candidate?.run_id||'尚無完整復驗通過版本'],['簽核身分',c.approval?.actor||'尚未簽核']])dl.append(el('dt',k),el('dd',v));$('detail').append(dl);for(const issue of c.issues){const d=el('div','', 'issue');d.append(el('strong',`${issue.severity}｜${issue.rule}`),el('p',`預期：${issue.expected}`),el('p',`實際：${issue.actual}`),el('p',`證據：${issue.evidence||'尚未取得'}`),el('p',`處理：${issue.resolution}`));$('detail').append(d);}const history=el('details','');history.append(el('summary','處置與簽核紀錄'));for(const h of c.history)history.append(el('p',`${h.at}｜${h.actor}｜${h.event}｜${h.reason||''}`));$('detail').append(history);$('actions').classList.remove('hidden');$('decision').value='ACKNOWLEDGE';$('reason').value='';$('decision').querySelector('[value="APPROVE"]').disabled=c.status!=='READY_REVIEW';$('submit').disabled=['PUBLISHED','PUBLISHING','CLOSED_NO_CHANGE'].includes(c.status);$('approval-note').textContent=c.status==='READY_REVIEW'?'核可只對上述候選雜湊有效；送出前仍會重新核對檔案與有效版本。':'尚未完成復驗的案件不可核可發布。';message('已載入案件。');}
async function submit(){if(!selected)return;const decision=$('decision').value,reason=$('reason').value.trim();if(reason.length<5)throw Error('請填寫至少 5 字的處理理由。');if(decision==='APPROVE'&&!confirm('確認核可目前顯示的候選雜湊，並在伺服器復核通過後發布？'))return;$('submit').disabled=true;try{const response=await api('/api/review/decision',{method:'POST',body:JSON.stringify({case_id:selected.case_id,revision:selected.revision,manifest_sha256:selected.candidate?.manifest_sha256,decision,reason})});const outcome=await response.json();if(outcome.status==='RESULT_PENDING'){message(outcome.message);return;}await loadCase(selected.case_id);await list();message('處置已記錄，請依最新狀態確認結果。');}finally{$('submit').disabled=['PUBLISHED','PUBLISHING','CLOSED_NO_CHANGE'].includes(selected?.status);}}
async function download(){if(!selected)return;const r=await api('/api/review/cases/'+encodeURIComponent(selected.case_id)+'/report');const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=selected.case_id+'-r'+selected.revision+'.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function boot(){config=await(await fetch('/review/config')).json();const q=new URLSearchParams(location.search);if(q.has('error'))throw Error('登入未完成，請重新登入。');if(q.has('code')){const saved=JSON.parse(sessionStorage.getItem('ntpc-review-oauth')||'null');history.replaceState(null,'','/review/');sessionStorage.removeItem('ntpc-review-oauth');if(!saved||q.get('state')!==saved.state||Date.now()-saved.at>600000)throw Error('登入驗證已過期或不符，請重新登入。');const r=await fetch(config.login_origin+'/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',client_id:config.client_id,code:q.get('code'),redirect_uri:config.redirect_uri,code_verifier:saved.verifier})});if(!r.ok)throw Error('登入權杖交換失敗，請重新登入。');token=(await r.json()).access_token;$('identity').textContent='已登入；實際權限由伺服器核對';$('refresh').disabled=false;$('login').textContent='重新登入';await list();}}
$('submit').textContent='送出處置';
for(const [id,fn] of [['login',login],['refresh',list],['submit',submit],['download',download]])$(id).addEventListener('click',()=>fn().catch(e=>message(e.message,true)));
boot().catch(e=>message(e.message,true));
